### ISSUE TITLE
Unable to load project in Microsoft Visual Studio Community 2015 

### ISSUE THREAD

**Issue by 10kTactics** [thelinuxlich/starwarrior_CSharp#9]
I used SourceTree to download this repository to c:/Users/UserName/Documents/Projects/starwarrior_CSharp

Opening StarWarrior.sln with Microsoft Visual Studio Community 2015 gives me this error and I am unable to build.

> Unsupported
> This version of Visual Studio is unable to open the following projects. The project types may not be installed or this version of Visual Studio may not support them. 
> For more information on enabling these project types or otherwise migrating your assets, please see the details in the "Migration Report" displayed after clicking OK.
> - StarWarrior, "C:\Users\UserName\Documents\Projects\starwarrior_CSharp\StarWarrior\StarWarrior\StarWarrior.csproj"
> 
> Non-functional changes required
> Visual Studio will automatically make non-functional changes to the following projects in order to enable them to open in Visual Studio 2015, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1. Project behavior will not be impacted.
> - StarWarrior, "C:\Users\UserName\Documents\Projects\starwarrior_CSharp\StarWarrior.sln"

**Comment by 10kTactics** [comment]
It appears the project type that Visual Studio 2015 is having trouble loading has to do with XNA, a discontinued Microsoft technology that looks last supported in Visual Studio 2010 maybe?

I'm guessing updating this project means porting to a new framework.

**Comment by thelinuxlich** [comment]
This example is very outdated, it doesn't match the actual API :(

**Comment by tpastor** [comment]
XNA for visual studio 2015
http://stackoverflow.com/questions/28008970/how-to-install-xna-in-visual-studio-2015-preview
